site_name: Read The Eximple Docs
copyright: Eximple
repo_url: https://github.com/docunid/readthemanuals.md/
docs_dir: 'docs'
pages:
- Home: index.md
- USER DOCUMENTATION:
   - 'CI/CD': 'cicd/index.md'
   - 'CoreOS': 'coreos/index.md'
   - RDDC:
      - 'k8s on pi': 'rddc/k8spi.md'
   - MIT:
      - 'Big Oh': 'mit/bigo.md'
      - 'Search': 'mit/search.md'
      - 'Sort': 'mit/sort.md'
   - Virtual Boxing: 'vb/network.md'
   - Mumbo Jumbo: 
      - mumbojumbo/dev.md
      - mumbojumbo/miscellaneous.md
      - mumbojumbo/m.2.md
      - mumbojumbo/node.md
      - mumbojumbo/proxy.md
      - mumbojumbo/staticwebsite.md
- About: about.md
theme: readthedocs
